server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/user_management
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: true

